-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
# NAME이 아니라 ID로 판단해야함
# 서브쿼리절 활용
WHERE  O.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
GROUP BY O.ANIMAL_ID
ORDER BY O.ANIMAL_ID;

# SELECT o.ANIMAL_ID, o.NAME
# FROM ANIMAL_OUTS o
# WHERE NOT o.ANIMAL_ID IN (
#     SELECT i.ANIMAL_ID
#     FROM ANIMAL_INS i)
# GROUP BY o.ANIMAL_ID
# ORDER BY o.ANIMAL_ID