-- 코드를 입력하세요
# SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
# FROM REST_INFO R1
# JOIN (
#     SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# ) R2 ON R1.FOOD_TYPE = R2.FOOD_TYPE AND R1.FAVORITES = R2.FAVORITES
# ORDER BY R1.FOOD_TYPE DESC;

select R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
from REST_INFO R1
inner join (
    select FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    from REST_INFO
    group by FOOD_TYPE) R2 on R1.FOOD_TYPE = R2.FOOD_TYPE AND R1.FAVORITES = R2.FAVORITES
order by R1.FOOD_TYPE desc;