n = int(input())
print(' @@@   @@@  '*n)
print('@   @ @   @ '*n)
print('@    @    @ '*n)
print('@         @ '*n)
print(' @       @  '*n)
print('  @     @   '*n)
print('   @   @    '*n)
print('    @ @     '*n)
print('     @      '*n)