SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
        ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
-- NUll값이 존재하지 않음. 공통된 REST_ID = 35만 결과로 출력됨.
-- inner join에 해당함.
INNER JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%"
-- REST_ID 35의 REVIWE SCORE가 AVG 집계함수로 들어가기 위해서 GROUP BY로 묶음.
GROUP BY R.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
        ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
-- NUll값이 존재하지 않음. 공통된 REST_ID = 35만 결과로 출력됨.
-- inner join에 해당함.
INNER JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
-- REST_ID 35의 REVIWE SCORE가 AVG 집계함수로 들어가기 위해서 GROUP BY로 묶음.
GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
ORDER BY SCORE DESC, I.FAVORITES DESC;


