-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O ON O.ANIMAL_ID = I.ANIMAL_ID
# in 기준 통합이므로 out에 없었다는 것은 in에만 있다는 것.
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3;