-- 코드를 입력하세요
# SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
# FROM FOOD_FACTORY
# WHERE ADDRESS LIKE '강원도%'
# ORDER BY FACTORY_ID ASC ;



select FACTORY_ID, FACTORY_NAME, ADDRESS
from FOOD_FACTORY
where ADDRESS LIKE "강원도%"
order by FACTORY_ID	asc ;