-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES;

# SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD b
# JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
# WHERE b.STATUS = 'DONE'
# GROUP BY u.USER_ID
# HAVING SUM(b.PRICE) >= 700000
# ORDER BY TOTAL_SALES;