-- 코드를 입력하세요
# SELECT A.FLAVOR AS FLAVOR
# FROM FIRST_HALF A
# INNER JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
# WHERE B.INGREDIENT_TYPE = "fruit_based" AND A.TOTAL_ORDER > 3000
# ORDER BY A.TOTAL_ORDER DESC;



select f.FLAVOR as FLAVOR
from FIRST_HALF f
inner join ICECREAM_INFO i on f.FLAVOR = i.FLAVOR
where f.TOTAL_ORDER > 3000 and i.INGREDIENT_TYPE = "fruit_based"
order by f.TOTAL_ORDER desc;